// Claude Code quota monitor for the ESP32-2432S028R ("Cheap Yellow Display").
//
// Polls a small HTTP bridge running on the Mac (bridge/quota_bridge.py) and
// renders the 5-hour and weekly usage windows as cards with gradient progress
// bars and live reset countdowns. No credentials live on the device: the bridge
// does all the reading of ~/.claude, and the ESP32 only ever sees percentages.
//
// All type is drawn with anti-aliased .vlw smooth fonts generated by
// tools/mkvlw.py. Each card is composed off-screen in a sprite and pushed in
// one go, so the per-second countdown never flickers.
//
// Touch: tap anywhere to force a refresh, hold for ~1s to blank the screen.

#include <Arduino.h>
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <SPI.h>
#include <TFT_eSPI.h>
#include <WiFi.h>
#include <XPT2046_Touchscreen.h>

#include "fonts/font_body_17.h"
#include "fonts/font_foot_14.h"
#include "fonts/font_num_36.h"
#include "fonts/font_pill_15.h"
#include "fonts/font_tab_11.h"
#include "fonts/font_title_27.h"
#include "secrets.h"
#include "theme.h"

// ---------------------------------------------------------------------------
// Hardware
// ---------------------------------------------------------------------------

// The touch controller sits on its own SPI bus on this board, separate from
// the panel, so it gets an explicit SPIClass rather than TFT_eSPI's TOUCH_CS.
constexpr uint8_t TOUCH_CLK = 25;
constexpr uint8_t TOUCH_MISO = 39;
constexpr uint8_t TOUCH_MOSI = 32;
constexpr uint8_t TOUCH_CS = 33;
constexpr uint8_t TOUCH_IRQ = 36;

constexpr uint8_t BACKLIGHT_PIN = 21;

TFT_eSPI tft;
TFT_eSprite card(&tft);
SPIClass touchSpi(HSPI);
XPT2046_Touchscreen touch(TOUCH_CS, TOUCH_IRQ);

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

constexpr int16_t SCREEN_W = 320;
constexpr int16_t SCREEN_H = 240;

// The vertical budget is unforgiving: 240px has to hold a header, two cards
// and a tab bar. Every constant below was chosen against the actual .vlw font
// heights (num_36 is 44px tall, foot_14 is 18) so nothing overlaps.
constexpr int16_t HEADER_H = 34;
constexpr int16_t CARD_X = 8;
constexpr int16_t CARD_W = SCREEN_W - 2 * CARD_X;
constexpr int16_t CARD_H = 76;
constexpr int16_t CARD_R = 12;
constexpr int16_t CARD_Y[2] = {38, 118};

constexpr int16_t PAD_X = 14;
constexpr int16_t PCT_CY = 26;   // vertical centre of the big percentage
constexpr int16_t PILL_Y = 8;
constexpr int16_t PILL_H = 22;
constexpr int16_t BAR_Y = 52;
constexpr int16_t BAR_H = 8;
constexpr int16_t RESET_CY = 66;
constexpr int16_t CLOCK_R = 5;   // reset-countdown clock glyph

// Bottom tab bar. Five slots across the full card width; only the first is
// wired to anything today, the rest are placeholders for planned screens.
constexpr int16_t NAV_Y = 198;
constexpr int16_t NAV_H = 40;
constexpr int16_t NAV_ITEMS = 5;
constexpr int16_t NAV_ITEM_W = CARD_W / NAV_ITEMS;
constexpr int16_t NAV_ICON = 18;

constexpr uint32_t POLL_INTERVAL_MS = 20000;
constexpr uint32_t RETRY_INTERVAL_MS = 5000;
constexpr uint32_t HTTP_TIMEOUT_MS = 6000;
constexpr uint32_t LONG_PRESS_MS = 1000;

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

struct Window {
  bool valid = false;
  int pct = -1;
  long secs = -1;  // seconds until reset, counted down locally between polls
};

struct QuotaState {
  bool ok = false;
  Window five;
  Window week;
  String profile;
  String source = "boot";
  uint64_t tokens5h = 0;
};

QuotaState state;
bool connected = false;
bool screenOn = true;
uint32_t lastPoll = 0;
uint32_t lastTick = 0;
uint32_t lastSuccess = 0;

// Cached values so a redraw only happens when something actually changed.
int drawnPct[2] = {-2, -2};
long drawnSecs[2] = {-2, -2};
int drawnBars = -1;
int drawnStatus = -1;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// Blend two RGB565 colours in the 5/6/5 domain. Used for the bar gradient.
uint16_t lerp565(uint16_t a, uint16_t b, uint8_t t) {
  const int ar = (a >> 11) & 0x1F, ag = (a >> 5) & 0x3F, ab = a & 0x1F;
  const int br = (b >> 11) & 0x1F, bg = (b >> 5) & 0x3F, bb = b & 0x1F;
  const int r = ar + ((br - ar) * t) / 255;
  const int g = ag + ((bg - ag) * t) / 255;
  const int bl = ab + ((bb - ab) * t) / 255;
  return (uint16_t)((r << 11) | (g << 5) | bl);
}

// Usage ramp: comfortable green, warning amber, alarming red.
void rampColors(int pct, uint16_t &from, uint16_t &to) {
  if (pct < 0) {
    from = to = COL_TRACK;
  } else if (pct >= 85) {
    from = COL_RED;
    to = COL_ORANGE;
  } else if (pct >= 60) {
    from = COL_ORANGE;
    to = COL_AMBER;
  } else {
    from = COL_GREEN;
    to = COL_LIME;
  }
}

// Compact, human-scaled duration: "6d 8h", "1h 22m", "47m 12s", "31s".
String formatDuration(long secs) {
  if (secs < 0) return "--";
  if (secs == 0) return "now";

  const long days = secs / 86400;
  const long hours = (secs % 86400) / 3600;
  const long minutes = (secs % 3600) / 60;
  const long seconds = secs % 60;

  char buf[24];
  if (days > 0) {
    snprintf(buf, sizeof(buf), "%ldd %ldh", days, hours);
  } else if (hours > 0) {
    snprintf(buf, sizeof(buf), "%ldh %02ldm", hours, minutes);
  } else if (minutes > 0) {
    snprintf(buf, sizeof(buf), "%ldm %02lds", minutes, seconds);
  } else {
    snprintf(buf, sizeof(buf), "%lds", seconds);
  }
  return String(buf);
}

void setBacklight(bool on) {
  digitalWrite(BACKLIGHT_PIN, on ? HIGH : LOW);
  screenOn = on;
}

// RSSI to a 0-3 bar count, using the usual "usable / good / excellent" cuts.
int signalBars() {
  if (WiFi.status() != WL_CONNECTED) return 0;
  const long rssi = WiFi.RSSI();
  if (rssi >= -60) return 3;
  if (rssi >= -70) return 2;
  if (rssi >= -80) return 1;
  return 0;
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

void drawMascot(int16_t x, int16_t y, uint8_t scale) {
  for (uint8_t row = 0; row < MASCOT_H; row++) {
    for (uint8_t col = 0; col < MASCOT_W; col++) {
      if (MASCOT[row][col] != '#') continue;
      // Shade top-to-bottom so it reads as art rather than a flat stamp.
      const uint16_t c = lerp565(COL_RED, COL_ORANGE, (row * 255) / (MASCOT_H - 1));
      tft.fillRect(x + col * scale, y + row * scale, scale, scale, c);
    }
  }
}

// The familiar three nested arcs. Drawn as circle segments clipped to the top
// half, with each arc dimmed when the signal does not reach that strength.
void drawWifiGlyph(int16_t cx, int16_t baseY, int bars) {
  for (int i = 0; i < 3; i++) {
    const int16_t r = 5 + i * 4;
    const uint16_t c = (i < bars) ? COL_TEXT : COL_RULE;
    // Two-pixel-thick arc: outer circle in the arc colour, inner punched back
    // out to the background, then everything below the origin erased.
    tft.drawCircle(cx, baseY, r, c);
    tft.drawCircle(cx, baseY, r - 1, c);
  }
  tft.fillRect(cx - 14, baseY + 1, 29, 14, COL_BG);
  tft.fillCircle(cx, baseY, 1, bars > 0 ? COL_TEXT : COL_RULE);
}

// Header status: wifi arcs, a word, and a dot in the matching colour.
void drawStatus(int bars) {
  const bool online = connected && state.ok;
  const uint16_t dot = online ? COL_GREEN : (connected ? COL_AMBER : COL_RED);
  const char *label = online ? "Online" : (connected ? "No data" : "Offline");

  tft.fillRect(SCREEN_W - 118, 2, 118, HEADER_H - 4, COL_BG);
  drawWifiGlyph(SCREEN_W - 102, HEADER_H / 2 + 5, bars);

  tft.loadFont(font_pill_15);
  tft.setTextDatum(MR_DATUM);
  tft.setTextColor(dot, COL_BG);
  tft.drawString(label, SCREEN_W - 22, HEADER_H / 2);
  tft.unloadFont();

  tft.fillCircle(SCREEN_W - 13, HEADER_H / 2, 4, dot);
}

void drawHeader() {
  tft.fillRect(0, 0, SCREEN_W, HEADER_H, COL_BG);
  drawMascot(10, (HEADER_H - MASCOT_H * 2) / 2, 2);

  tft.loadFont(font_title_27);
  // A failed loadFont falls back to the default bitmap face without warning,
  // which is the difference between smooth type and jagged type on screen.
  Serial.printf("title font height=%d (expect 34)\n", tft.fontHeight());
  tft.setTextDatum(ML_DATUM);
  tft.setTextColor(COL_TEXT, COL_BG);
  tft.drawString("Usage", 10 + MASCOT_W * 2 + 9, HEADER_H / 2 - 1);
  tft.unloadFont();

  drawnBars = -1;
  drawnStatus = -1;
}

void drawSignalIfChanged() {
  const int bars = signalBars();
  const int status = (connected ? 1 : 0) + (state.ok ? 2 : 0);
  if (bars == drawnBars && status == drawnStatus) return;
  drawnBars = bars;
  drawnStatus = status;
  drawStatus(bars);
}

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

void drawBar(const Window &win) {
  const int16_t barX = PAD_X;
  const int16_t barW = CARD_W - 2 * PAD_X;
  const int16_t radius = BAR_H / 2;

  card.fillRoundRect(barX, BAR_Y, barW, BAR_H, radius, COL_TRACK);
  if (!win.valid || win.pct <= 0) return;

  uint16_t from, to;
  rampColors(win.pct, from, to);

  int16_t fill = (int32_t)barW * min(win.pct, 100) / 100;
  if (fill < BAR_H) fill = BAR_H;  // keep both rounded caps intact at 1-2%

  // Lay the rounded shape down in the start colour, sweep the straight middle
  // section with the gradient, then cap the right end in the finish colour so
  // the rounding survives.
  card.fillRoundRect(barX, BAR_Y, fill, BAR_H, radius, from);
  for (int16_t i = radius; i < fill - radius; i++) {
    const uint8_t t = (uint8_t)((int32_t)i * 255 / max<int16_t>(fill - 1, 1));
    card.drawFastVLine(barX + i, BAR_Y, BAR_H, lerp565(from, to, t));
  }
  card.fillCircle(barX + fill - radius - 1, BAR_Y + radius, radius, to);
}

// A clock face in the card's own accent colour, sitting left of the countdown.
void drawClock(int16_t cx, int16_t cy, uint16_t colour) {
  card.drawCircle(cx, cy, CLOCK_R, colour);
  card.drawCircle(cx, cy, CLOCK_R - 1, colour);
  card.drawFastVLine(cx, cy - 3, 4, colour);
  card.drawFastHLine(cx, cy, 3, colour);
}

// The affordance from the reference: a thin ">" hinting at a detail screen.
void drawChevron(int16_t cx, int16_t cy) {
  for (int16_t i = 0; i < 6; i++) {
    card.drawPixel(cx - 2 + i / 2, cy - 6 + i, COL_CHEVRON);
    card.drawPixel(cx - 1 + i / 2, cy - 6 + i, COL_CHEVRON);
    card.drawPixel(cx + 3 - i / 2, cy + i, COL_CHEVRON);
    card.drawPixel(cx + 4 - i / 2, cy + i, COL_CHEVRON);
  }
}

void drawCard(int index, const Window &win, const char *badge) {
  const uint16_t pillBg = index == 0 ? COL_PILL_BG : COL_PILL2_BG;
  const uint16_t pillTx = index == 0 ? COL_PILL_TX : COL_PILL2_TX;

  card.fillSprite(COL_BG);
  card.fillRoundRect(0, 0, CARD_W, CARD_H, CARD_R, COL_CARD);
  card.drawRoundRect(0, 0, CARD_W, CARD_H, CARD_R, COL_CARD_EDGE);

  // Percentage.
  card.loadFont(font_num_36);
  card.setTextDatum(ML_DATUM);
  card.setTextColor(COL_TEXT, COL_CARD);
  card.drawString(win.valid ? String(win.pct) + "%" : String("--"), PAD_X, PCT_CY);
  card.unloadFont();

  // Badge pill, right aligned, with room kept clear for the chevron.
  drawChevron(CARD_W - PAD_X - 4, PILL_Y + PILL_H / 2);

  card.loadFont(font_pill_15);
  const int16_t pillW = card.textWidth(badge) + 24;
  const int16_t pillX = CARD_W - PAD_X - 16 - pillW;
  card.fillRoundRect(pillX, PILL_Y, pillW, PILL_H, PILL_H / 2, pillBg);
  card.setTextDatum(MC_DATUM);
  card.setTextColor(pillTx, pillBg);
  card.drawString(badge, pillX + pillW / 2, PILL_Y + PILL_H / 2);
  card.unloadFont();

  drawBar(win);

  // Reset countdown, keyed to the same colour ramp as the bar so the card
  // reads as one object rather than three unrelated widgets.
  uint16_t accent, unused;
  rampColors(win.valid ? win.pct : -1, accent, unused);
  drawClock(PAD_X + CLOCK_R, RESET_CY, accent);

  card.loadFont(font_foot_14);
  card.setTextDatum(ML_DATUM);
  card.setTextColor(COL_MUTED, COL_CARD);
  card.drawString("Resets in " + formatDuration(win.secs), PAD_X + 2 * CLOCK_R + 7,
                  RESET_CY);
  card.unloadFont();

  card.pushSprite(CARD_X, CARD_Y[index]);
}

void drawCardIfChanged(int index, const Window &win, const char *badge) {
  if (win.pct == drawnPct[index] && win.secs == drawnSecs[index]) return;
  drawnPct[index] = win.pct;
  drawnSecs[index] = win.secs;
  drawCard(index, win, badge);
}

// ---------------------------------------------------------------------------
// Footer
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Tab bar
// ---------------------------------------------------------------------------

// A four-point sparkle: two opposing triangle pairs sharing a centre.
void drawSparkle(int16_t cx, int16_t cy, int16_t r, uint16_t colour) {
  tft.fillTriangle(cx, cy - r, cx - r / 2, cy, cx + r / 2, cy, colour);
  tft.fillTriangle(cx, cy + r, cx - r / 2, cy, cx + r / 2, cy, colour);
  tft.fillTriangle(cx - r, cy, cx, cy - r / 2, cx, cy + r / 2, colour);
  tft.fillTriangle(cx + r, cy, cx, cy - r / 2, cx, cy + r / 2, colour);
}

void drawTabIcon(int index, int16_t x, int16_t y) {
  const int16_t cx = x + NAV_ICON / 2;
  const int16_t cy = y + NAV_ICON / 2;

  switch (index) {
    case 0:  // Claude: a sparkle, with a smaller one trailing it.
      tft.fillRoundRect(x, y, NAV_ICON, NAV_ICON, 5, COL_TAB1_BG);
      drawSparkle(cx + 1, cy + 1, 6, COL_ACCENT);
      drawSparkle(cx - 5, cy - 4, 3, COL_AMBER);
      break;
    case 1:  // Weekly usage: a three-column bar chart.
      tft.fillRoundRect(x, y, NAV_ICON, NAV_ICON, 5, COL_TAB2_BG);
      tft.fillRoundRect(cx - 6, cy - 1, 3, 7, 1, COL_TAB2_FG);
      tft.fillRoundRect(cx - 1, cy - 6, 3, 12, 1, COL_TAB2_FG);
      tft.fillRoundRect(cx + 4, cy - 4, 3, 10, 1, COL_TAB2_FG);
      break;
    case 2:  // Weather: sun peeking over a cloud.
      tft.fillRoundRect(x, y, NAV_ICON, NAV_ICON, 5, COL_TAB3_BG);
      tft.fillCircle(cx + 4, cy - 4, 3, COL_AMBER);
      tft.fillCircle(cx - 3, cy + 1, 4, COL_TAB3_FG);
      tft.fillCircle(cx + 3, cy + 2, 3, COL_TAB3_FG);
      tft.fillRect(cx - 3, cy + 1, 7, 4, COL_TAB3_FG);
      break;
    case 3:  // Crypto: a bitcoin B, drawn rather than typeset -- loading a
             // font here would unload the label font mid-loop and drop the
             // remaining tab labels back to the jagged built-in face.
      tft.fillRoundRect(x, y, NAV_ICON, NAV_ICON, 5, COL_TAB4_BG);
      tft.fillRect(cx - 4, cy - 5, 2, 10, COL_TAB4_FG);      // stem
      tft.fillRect(cx - 4, cy - 5, 5, 2, COL_TAB4_FG);       // upper bowl
      tft.fillRect(cx + 1, cy - 4, 2, 3, COL_TAB4_FG);
      tft.fillRect(cx - 4, cy - 1, 6, 2, COL_TAB4_FG);       // waist
      tft.fillRect(cx + 2, cy, 2, 3, COL_TAB4_FG);           // lower bowl
      tft.fillRect(cx - 4, cy + 3, 6, 2, COL_TAB4_FG);
      tft.fillRect(cx - 2, cy - 8, 2, 3, COL_TAB4_FG);       // vertical strokes
      tft.fillRect(cx + 1, cy - 8, 2, 3, COL_TAB4_FG);
      tft.fillRect(cx - 2, cy + 5, 2, 3, COL_TAB4_FG);
      tft.fillRect(cx + 1, cy + 5, 2, 3, COL_TAB4_FG);
      break;
    default:  // Setting: a gear.
      tft.fillRoundRect(x, y, NAV_ICON, NAV_ICON, 5, COL_TAB5_BG);
      for (int i = 0; i < 4; i++) {
        const int16_t dx = (i == 0) ? -7 : (i == 1) ? 7 : 0;
        const int16_t dy = (i == 2) ? -7 : (i == 3) ? 7 : 0;
        tft.fillRoundRect(cx + dx - 2, cy + dy - 2, 4, 4, 1, COL_TAB5_FG);
      }
      tft.fillCircle(cx, cy, 6, COL_TAB5_FG);
      tft.fillCircle(cx, cy, 2, COL_TAB5_BG);
      break;
  }
}

// Static chrome: drawn once per full redraw, never on the per-second tick.
void drawNavBar() {
  static const char *labels[NAV_ITEMS] = {"Claude", "Weekly", "Weather", "Crypto",
                                          "Setting"};
  constexpr int active = 0;

  tft.fillRect(0, NAV_Y - 4, SCREEN_W, SCREEN_H - NAV_Y + 4, COL_BG);
  tft.drawRoundRect(CARD_X, NAV_Y, CARD_W, NAV_H, 10, COL_NAV_EDGE);

  // Icons first, then every label in one pass: loading a font inside the icon
  // switch would unload this one and silently downgrade the rest of the row.
  for (int i = 0; i < NAV_ITEMS; i++) {
    const int16_t cx = CARD_X + i * NAV_ITEM_W + NAV_ITEM_W / 2;
    drawTabIcon(i, cx - NAV_ICON / 2, NAV_Y + 4);
  }

  tft.loadFont(font_tab_11);
  tft.setTextDatum(MC_DATUM);
  for (int i = 0; i < NAV_ITEMS; i++) {
    const int16_t cx = CARD_X + i * NAV_ITEM_W + NAV_ITEM_W / 2;
    tft.setTextColor(i == active ? COL_ACCENT : COL_NAV_TX, COL_BG);
    tft.drawString(labels[i], cx, NAV_Y + 29);
  }
  tft.unloadFont();

  // Underline the current tab.
  const int16_t ax = CARD_X + active * NAV_ITEM_W + NAV_ITEM_W / 2;
  tft.fillRoundRect(ax - 13, NAV_Y + NAV_H - 4, 26, 2, 1, COL_ACCENT);
}

void render() {
  if (!screenOn) return;
  drawSignalIfChanged();
  drawCardIfChanged(0, state.five, "Current");
  drawCardIfChanged(1, state.week, "Weekly");
}

void redrawAll() {
  tft.fillScreen(COL_BG);
  drawHeader();
  drawNavBar();
  drawnPct[0] = drawnPct[1] = -2;
  drawnSecs[0] = drawnSecs[1] = -2;
  render();
}

void showBootScreen(const char *message) {
  tft.fillScreen(COL_BG);
  drawHeader();
  tft.loadFont(font_body_17);
  tft.setTextDatum(MC_DATUM);
  tft.setTextColor(COL_MUTED, COL_BG);
  tft.drawString(message, SCREEN_W / 2, SCREEN_H / 2);
  tft.unloadFont();
}

// ---------------------------------------------------------------------------
// Networking
// ---------------------------------------------------------------------------

bool fetchQuota() {
  if (WiFi.status() != WL_CONNECTED) return false;

  HTTPClient http;
  http.setTimeout(HTTP_TIMEOUT_MS);
  http.setConnectTimeout(HTTP_TIMEOUT_MS);
  if (!http.begin(BRIDGE_URL)) {
    state.ok = false;
    state.source = "bad url";
    return false;
  }

  const int code = http.GET();
  if (code != HTTP_CODE_OK) {
    state.ok = false;
    state.source = (code < 0) ? "unreachable" : ("http " + String(code));
    http.end();
    return false;
  }

  JsonDocument doc;
  const DeserializationError err = deserializeJson(doc, http.getStream());
  http.end();

  if (err) {
    state.ok = false;
    state.source = "bad json";
    return false;
  }

  state.ok = doc["ok"] | false;
  state.source = doc["src"].as<String>();
  state.profile = doc["profile"].as<String>();
  state.tokens5h = doc["tok5h"] | 0ULL;

  // A null pct means the bridge could not obtain a trustworthy number; show
  // "--" rather than a stale or invented percentage.
  state.five.pct = doc["five"]["pct"].isNull() ? -1 : doc["five"]["pct"].as<int>();
  state.five.secs = doc["five"]["secs"].isNull() ? -1 : doc["five"]["secs"].as<long>();
  state.five.valid = state.five.pct >= 0;

  state.week.pct = doc["week"]["pct"].isNull() ? -1 : doc["week"]["pct"].as<int>();
  state.week.secs = doc["week"]["secs"].isNull() ? -1 : doc["week"]["secs"].as<long>();
  state.week.valid = state.week.pct >= 0;

  if (state.ok) lastSuccess = millis();
  return state.ok;
}

// ---------------------------------------------------------------------------
// Touch
// ---------------------------------------------------------------------------

void handleTouch() {
  static bool wasDown = false;
  static uint32_t pressStart = 0;
  static bool longFired = false;

  const bool isDown = touch.touched();

  if (isDown && !wasDown) {
    pressStart = millis();
    longFired = false;
  }

  if (isDown && !longFired && (millis() - pressStart) > LONG_PRESS_MS) {
    longFired = true;
    setBacklight(!screenOn);
    if (screenOn) redrawAll();
  }

  if (!isDown && wasDown && !longFired) {
    if (!screenOn) {
      setBacklight(true);
      redrawAll();
    }
    lastPoll = 0;  // force an immediate refresh
  }

  wasDown = isDown;
}

// ---------------------------------------------------------------------------
// Arduino entry points
// ---------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);
  delay(100);

  pinMode(BACKLIGHT_PIN, OUTPUT);
  setBacklight(true);

  tft.init();
  tft.setRotation(1);  // landscape, USB on the left
  tft.fillScreen(COL_BG);

  card.setColorDepth(16);
  if (!card.createSprite(CARD_W, CARD_H)) {
    Serial.println("card sprite allocation failed");
  }

  touchSpi.begin(TOUCH_CLK, TOUCH_MISO, TOUCH_MOSI, TOUCH_CS);
  touch.begin(touchSpi);
  touch.setRotation(1);

  showBootScreen("connecting to wifi");

  WiFi.mode(WIFI_STA);
  WiFi.setSleep(false);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  const uint32_t deadline = millis() + 20000;
  while (WiFi.status() != WL_CONNECTED && millis() < deadline) {
    delay(250);
    Serial.print(".");
  }

  connected = WiFi.status() == WL_CONNECTED;
  Serial.println();
  if (connected) {
    Serial.printf("wifi ok, ip=%s\n", WiFi.localIP().toString().c_str());
    Serial.printf("bridge=%s\n", BRIDGE_URL);
  } else {
    Serial.println("wifi failed, will keep retrying");
  }

  redrawAll();
}

void loop() {
  handleTouch();

  if (WiFi.status() != WL_CONNECTED) {
    if (connected) {
      connected = false;
      drawnStatus = -1;
    }
    WiFi.reconnect();
    render();
    delay(500);
    return;
  }

  if (!connected) {
    connected = true;
    drawnStatus = -1;
  }

  const uint32_t now = millis();
  const uint32_t interval = state.ok ? POLL_INTERVAL_MS : RETRY_INTERVAL_MS;
  if (lastPoll == 0 || now - lastPoll >= interval) {
    lastPoll = now;
    fetchQuota();
    render();
  }

  // Count the reset timers down locally so they tick smoothly between polls.
  if (now - lastTick >= 1000) {
    lastTick = now;
    if (state.five.secs > 0) state.five.secs--;
    if (state.week.secs > 0) state.week.secs--;
    render();
  }

  delay(20);
}
