// Palette and pixel art for the quota display.
#pragma once

#include <Arduino.h>

// Generated by tools/mkpalette.py -- do not hand-edit the values. Packing
// 8/8/8 into 5/6/5 by hand is how a dark green (#386800) silently became a
// glaring lime (#31AA00) on the board while the build stayed quiet.
// Regenerate:  tools/mkpalette.py        Verify:  tools/mkpalette.py --check
constexpr uint16_t COL_BG        = 0x0000;  // #000000  page background
constexpr uint16_t COL_CARD      = 0x10A2;  // #141416  card fill
constexpr uint16_t COL_CARD_EDGE = 0x2125;  // #26262A  1px card hairline
constexpr uint16_t COL_TEXT      = 0xFFFF;  // #FFFFFF
constexpr uint16_t COL_MUTED     = 0x9CD4;  // #9A9AA0  secondary type
constexpr uint16_t COL_TRACK     = 0x2928;  // #2E2740  progress bar groove
constexpr uint16_t COL_RULE      = 0x39C8;  // #3A3A44  inactive glyph
constexpr uint16_t COL_CHEVRON   = 0x5ACC;  // #5A5A62

constexpr uint16_t COL_PILL_BG   = 0x396A;  // #3B2E52  Current badge
constexpr uint16_t COL_PILL_TX   = 0xCDFD;  // #CDBCEC
constexpr uint16_t COL_PILL2_BG  = 0x2A42;  // #2C4A10  Weekly badge
constexpr uint16_t COL_PILL2_TX  = 0xB74D;  // #B6E86A

constexpr uint16_t COL_LIME      = 0xC747;  // #C7E93B  usage ramp
constexpr uint16_t COL_GREEN     = 0x7EC7;  // #7FD93C
constexpr uint16_t COL_AMBER     = 0xFD84;  // #FFB020
constexpr uint16_t COL_ORANGE    = 0xFC47;  // #FF8A3D
constexpr uint16_t COL_RED       = 0xF245;  // #F04A2A
constexpr uint16_t COL_ACCENT    = 0xF405;  // #F5822E  brand orange

constexpr uint16_t COL_NAV_EDGE  = 0x18E4;  // #1E1E22  tab bar hairline
constexpr uint16_t COL_NAV_TX    = 0x8C72;  // #8E8E94  inactive tab label

constexpr uint16_t COL_TAB1_BG   = 0x4101;  // #40230A  Claude tile
constexpr uint16_t COL_TAB2_BG   = 0x20E8;  // #241E44  Weekly tile
constexpr uint16_t COL_TAB2_FG   = 0x8C1F;  // #8C83FF
constexpr uint16_t COL_TAB3_BG   = 0x08E7;  // #0E1E3C  Weather tile
constexpr uint16_t COL_TAB3_FG   = 0x3DBF;  // #3CB4FF
constexpr uint16_t COL_TAB4_BG   = 0x2920;  // #2A2404  Crypto tile
constexpr uint16_t COL_TAB4_FG   = 0xFEA0;  // #FFD400
constexpr uint16_t COL_TAB5_BG   = 0x2966;  // #2C2C30  Setting tile
constexpr uint16_t COL_TAB5_FG   = 0xB5B7;  // #B4B4BA

// The header mascot: a blocky robot with two eye slots, stubby antennae and
// four legs. One character per pixel; '#' is opaque, anything else is clear.
// Drawn at scale 2, so this grid is 28x24 on screen.
constexpr uint8_t MASCOT_W = 14;
constexpr uint8_t MASCOT_H = 12;
constexpr char MASCOT[MASCOT_H][MASCOT_W + 1] = {
    "...#......#...",
    "...#......#...",
    "..##########..",
    ".############.",
    "##############",
    "##..######..##",
    "##..######..##",
    "##############",
    "##############",
    ".############.",
    ".##.##..##.##.",
    ".##.##..##.##.",
};
