// The palette, as plain RGB888.
//
// The TFT_eSPI build kept these as pre-packed RGB565 words generated by a
// script, because packing 8/8/8 into 5/6/5 by hand is how a dark green
// silently became a glaring lime on the board. LVGL takes RGB888 and does the
// conversion itself at draw time, so that whole class of mistake -- and the
// generator that existed to prevent it -- goes away.
#pragma once

#include <lvgl.h>

#include "../config.h"
#include "../model.h"

namespace theme {

constexpr uint32_t BG = 0x000000;
constexpr uint32_t CARD = 0x141416;
constexpr uint32_t CARD_EDGE = 0x26262A;
constexpr uint32_t TEXT = 0xFFFFFF;
constexpr uint32_t MUTED = 0x9A9AA0;
constexpr uint32_t TRACK = 0x2E2740;

constexpr uint32_t PILL_SESSION_BG = 0x3B2E52;
constexpr uint32_t PILL_SESSION_TX = 0xCDBCEC;
constexpr uint32_t PILL_WEEKLY_BG = 0x2C4A10;
constexpr uint32_t PILL_WEEKLY_TX = 0xB6E86A;

constexpr uint32_t LIME = 0xC7E93B;
constexpr uint32_t GREEN = 0x7FD93C;
constexpr uint32_t AMBER = 0xFFB020;
constexpr uint32_t ORANGE = 0xFF8A3D;
constexpr uint32_t RED = 0xF04A2A;
constexpr uint32_t ACCENT = 0xF5822E;

constexpr uint32_t NAV_EDGE = 0x1E1E22;
constexpr uint32_t NAV_INACTIVE = 0x8E8E94;

// The Ramp: utilization to colour, comfortable through alarming. Returns the
// pair the progress bar sweeps between; the countdown beside it takes `from`
// so the two read as one object rather than as unrelated widgets.
inline void ramp(int8_t utilization, uint32_t &from, uint32_t &to) {
  if (utilization < 0) {
    from = to = TRACK;
  } else if (utilization >= RAMP_ALARM_PCT) {
    from = RED;
    to = ORANGE;
  } else if (utilization >= RAMP_WARN_PCT) {
    from = ORANGE;
    to = AMBER;
  } else {
    from = GREEN;
    to = LIME;
  }
}

inline lv_color_t colour(uint32_t rgb) { return lv_color_hex(rgb); }

}  // namespace theme
