// The palette, as named roles rather than literal RGB.
//
// The TFT_eSPI build kept these as pre-packed RGB565 words generated by a
// script, because packing 8/8/8 into 5/6/5 by hand is how a dark green
// silently became a glaring lime on the board. LVGL takes RGB888 and does the
// conversion itself at draw time, so that whole class of mistake -- and the
// generator that existed to prevent it -- goes away.
//
// Every colour in the UI names a Role, not a value. The RGB behind a Role
// depends on the active Mode (Dark or Light) and is resolved at draw time by
// colour(). Call sites still write theme::TEXT, theme::RED, ...; those names
// are now small indices into the active palette rather than constants, so the
// same code draws either Mode without a line changing. Two mechanisms carry a
// Mode switch to the pixels without a rebuild (see ADR-0003, no realloc):
//
//   - Structural colours set once at build (card fills, borders, static text)
//     ride a shared lv_style_t per Role; toggle() rewrites the styles in place.
//   - Semantic colours chosen from a value (the Ramp, an up/down tint, a feed's
//     health) are set imperatively and cached by the change-detecting screens.
//     toggle() bumps generation(); a screen whose cached generation moved
//     forgets its sentinels and repaints, because a Role's RGB shifted under a
//     value that did not.
#pragma once

#include <lvgl.h>

#include "../config.h"
#include "../model.h"

namespace theme {

// The Roles, in the order the palette tables in theme.cpp list them. Adding a
// Role means adding a column to both tables at the same index.
enum Role : uint32_t {
  BG = 0,
  CARD,
  CARD_EDGE,
  TEXT,
  MUTED,
  TRACK,
  PILL_SESSION_BG,
  PILL_SESSION_TX,
  PILL_WEEKLY_BG,
  PILL_WEEKLY_TX,
  LIME,
  GREEN,
  AMBER,
  ORANGE,
  RED,
  ACCENT,
  NAV_EDGE,
  NAV_INACTIVE,
  // The disc behind a weather glyph. Blends into the card in Dark (the glyphs
  // read fine on a dark surface); goes dark in Light so a pale sun or a white
  // snowflake has something to sit against instead of washing into the card.
  GLYPH_DISC,
  ROLE_COUNT,
};

enum class Mode : uint8_t { Dark = 0, Light = 1 };

// The RGB888 behind a Role in the active Mode, and the LVGL colour for it.
uint32_t valueOf(uint32_t role);
inline lv_color_t colour(uint32_t role) { return lv_color_hex(valueOf(role)); }

// Loads the persisted Mode and prepares the palette. Call after lv_init() and
// before any screen is built, so the widget helpers attach styles that already
// carry the right Mode.
void init();

// Flip Dark<->Light: persist the choice, rewrite every shared style in place
// (no realloc), and bump generation() so the change-detecting screens repaint
// their semantic colours. Cheap enough to call straight from a touch handler.
void toggle();

Mode mode();
const char *modeName();  // "Dark" / "Light"

// Bumped by every toggle(). A screen compares this against its own cached copy;
// when they differ it forgets its change-detection sentinels for one pass so
// the Roles that moved are redrawn even though the underlying values did not.
uint8_t generation();

// The shared styles the widget helpers attach so structural colours follow the
// Mode without a rebuild. One lv_style_t per (property, Role), created the
// first time a Role is asked for and rewritten in place by toggle().
lv_style_t *bgStyle(uint32_t role);
lv_style_t *textStyle(uint32_t role);
lv_style_t *borderStyle(uint32_t role);

// The Ramp: utilization to colour Roles, comfortable through alarming. Returns
// the pair the progress bar sweeps between; the countdown beside it takes
// `from` so the two read as one object rather than as unrelated widgets.
inline void ramp(int8_t utilization, uint32_t &from, uint32_t &to) {
  if (utilization < 0) {
    from = to = TRACK;
  } else if (utilization >= RAMP_ALARM_PCT) {
    from = RED;
    to = ORANGE;
  } else if (utilization >= RAMP_WARN_PCT) {
    from = ORANGE;
    to = AMBER;
  } else {
    from = GREEN;
    to = LIME;
  }
}

}  // namespace theme
