// Generated by tools/mkicons_lvgl.py -- do not hand-edit.
// Regenerate after changing any artwork:  tools/mkicons_lvgl.py
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t icon_claude;
extern const lv_image_dsc_t icon_weekly;
extern const lv_image_dsc_t icon_weather;
extern const lv_image_dsc_t icon_crypto;
extern const lv_image_dsc_t icon_setting;
extern const lv_image_dsc_t img_mascot;
extern const lv_image_dsc_t glyph_clock;
extern const lv_image_dsc_t glyph_wifi;

#ifdef __cplusplus
}
#endif
