// Generated by tools/mkicons_lvgl.py -- do not hand-edit.
// Regenerate after changing any artwork:  python3 tools/mkicons_lvgl.py
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t icon_claude;
extern const lv_image_dsc_t icon_weekly;
extern const lv_image_dsc_t icon_weather;
extern const lv_image_dsc_t icon_crypto;
extern const lv_image_dsc_t icon_stock;
extern const lv_image_dsc_t icon_setting;
extern const lv_image_dsc_t icon_usage_hdr;
extern const lv_image_dsc_t img_mascot;
extern const lv_image_dsc_t glyph_clock;
extern const lv_image_dsc_t glyph_wifi;
extern const lv_image_dsc_t glyph_wifi_high;
extern const lv_image_dsc_t glyph_wifi_low;
extern const lv_image_dsc_t glyph_wifi_off;
extern const lv_image_dsc_t glyph_brightness;
extern const lv_image_dsc_t glyph_moon;
extern const lv_image_dsc_t wx_clear_day;
extern const lv_image_dsc_t wx_clear_night;
extern const lv_image_dsc_t wx_partly_day;
extern const lv_image_dsc_t wx_partly_night;
extern const lv_image_dsc_t wx_cloudy;
extern const lv_image_dsc_t wx_fog;
extern const lv_image_dsc_t wx_rain;
extern const lv_image_dsc_t wx_snow;
extern const lv_image_dsc_t wx_storm;
extern const lv_image_dsc_t coin_btc;
extern const lv_image_dsc_t coin_eth;
extern const lv_image_dsc_t coin_bnb;
extern const lv_image_dsc_t icon_weekly_hdr;
extern const lv_image_dsc_t icon_weather_hdr;
extern const lv_image_dsc_t icon_crypto_hdr;
extern const lv_image_dsc_t icon_stock_hdr;
extern const lv_image_dsc_t icon_setting_hdr;
extern const lv_image_dsc_t coin_btc_hdr;
extern const lv_image_dsc_t coin_eth_hdr;
extern const lv_image_dsc_t coin_bnb_hdr;
extern const lv_image_dsc_t logo_aapl;
extern const lv_image_dsc_t logo_nvda;
extern const lv_image_dsc_t logo_tsla;
extern const lv_image_dsc_t logo_goog;
extern const lv_image_dsc_t logo_msft;

#ifdef __cplusplus
}
#endif
