// Generated by tools/mkfont_lvgl.py -- do not hand-edit.
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(font_inter_36);
LV_FONT_DECLARE(font_inter_27);
LV_FONT_DECLARE(font_inter_17);
LV_FONT_DECLARE(font_inter_15);
LV_FONT_DECLARE(font_inter_14);
LV_FONT_DECLARE(font_inter_12);

#ifdef __cplusplus
}
#endif
