#!/usr/bin/env python3
"""Generate LVGL fonts from Inter.ttf, as C sources under firmware/src/ui/fonts.

This replaces mkvlw.py, which produced TFT_eSPI's .vlw format. LVGL cannot read
.vlw at all, so the type had to be regenerated rather than ported.

The actual conversion is done by lv_font_conv, which is a Node tool run through
npx -- there is no Python equivalent that produces LVGL's glyph tables. This
wrapper exists to pin the settings that matter and to keep one command for
regenerating every size, rather than five long npx invocations nobody remembers.

Sizes come from the design: the big percentage, the header, body copy, the pill
badges and the reset countdown. The navbar has no labels, so the 11px face that
the TFT_eSPI build carried is not regenerated.

Usage:
    tools/mkfont_lvgl.py            regenerate every size
    tools/mkfont_lvgl.py --check    verify the checked-in files are current
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_TTF = ROOT / "fonts" / "Inter.ttf"
OUT_DIR = ROOT / "firmware" / "src" / "ui" / "fonts"

# ASCII printable, plus the degree sign the Weather screen needs. Thai glyphs
# would add roughly 150KB and LVGL's text engine does not stack Thai vowels and
# tone marks correctly anyway, so the UI is English throughout.
#
# U+00B0 is one glyph and about forty bytes a face. Spelling the temperature
# "30.2 C" instead would have saved that and read like a chemistry answer.
SYMBOLS_RANGE = "0x20-0x7E,0xB0"

# 4 bits per pixel: 16 levels of anti-aliasing. 8bpp doubles the flash cost for
# a difference that is not visible on a 240px panel at arm's length.
BPP = 4

FACES = [
    ("font_inter_36", 36),  # the big percentage
    ("font_inter_27", 27),  # "Usage" in the header
    ("font_inter_17", 17),  # body copy
    ("font_inter_15", 15),  # pill badges, status word
    ("font_inter_14", 14),  # captions
    ("font_inter_12", 12),  # reset countdown
]


def convert(name: str, size: int, dest: Path) -> None:
    cmd = [
        "npx",
        "--yes",
        "lv_font_conv@1.5.3",
        "--font", str(SOURCE_TTF),
        "--size", str(size),
        "--bpp", str(BPP),
        "--range", SYMBOLS_RANGE,
        "--format", "lvgl",
        "--lv-include", "lvgl.h",
        "--no-compress",  # decompression costs RAM at draw time; flash is cheap here
        "--force-fast-kern-format",
        "-o", str(dest),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"lv_font_conv failed for {name} at {size}px")


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12] if path.exists() else "-"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a temporary directory and report drift without writing",
    )
    args = parser.parse_args()

    if not SOURCE_TTF.exists():
        raise SystemExit(f"missing {SOURCE_TTF}")
    if shutil.which("npx") is None:
        raise SystemExit("npx not found -- lv_font_conv needs Node installed")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    scratch = OUT_DIR / ".check" if args.check else None
    if scratch:
        scratch.mkdir(exist_ok=True)

    drift = False
    for name, size in FACES:
        final = OUT_DIR / f"{name}.c"
        target = (scratch / f"{name}.c") if scratch else final
        before = digest(final)
        convert(name, size, target)
        after = digest(target)

        if args.check:
            changed = before != after
            drift = drift or changed
            print(f"{name:16} {size:>3}px  {'DRIFT' if changed else 'ok':>5}  {before}")
        else:
            kb = target.stat().st_size / 1024
            print(f"{name:16} {size:>3}px  {kb:7.1f} KB  {after}")

    if scratch:
        shutil.rmtree(scratch)
        if drift:
            print("\ncheckedin fonts differ from a fresh conversion", file=sys.stderr)
            return 1
        return 0

    # lv_font_conv emits the definitions but no header, and the faces are used
    # from C++ where a missing declaration is an error rather than a guess.
    decls = "\n".join(f"LV_FONT_DECLARE({name});" for name, _ in FACES)
    (OUT_DIR / "ui_fonts.h").write_text(
        f"""// Generated by tools/mkfont_lvgl.py -- do not hand-edit.
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {{
#endif

{decls}

#ifdef __cplusplus
}}
#endif
""",
        encoding="utf-8",
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
