#!/usr/bin/env python3
"""Generate TFT_eSPI smooth fonts (.vlw) from a TTF, as C headers.

TFT_eSPI's GFX "Free Fonts" are 1-bit masks, which is why text drawn with them
has hard, jagged edges. The .vlw format stores an 8-bit coverage value per
pixel, so the library can blend glyphs against the background and the result
looks like real type.

The format, as parsed by TFT_eSPI's Smooth_font.cpp:

    header   6 x int32 big-endian: gCount, version, fontSize, 0, ascent, descent
    metrics  gCount x 7 x int32:   unicode, height, width, xAdvance, dY, dX, 0
    bitmaps  concatenated, 1 byte of coverage per pixel, glyph order

Usage:
    mkvlw.py FONT.ttf --size 44 --name inter_bold_44 --chars '0123456789%' \
             --variation Bold --out ../firmware/src/fonts
"""

from __future__ import annotations

import argparse
import string
import struct
import sys
from pathlib import Path

from PIL import ImageFont

VLW_VERSION = 11


def build_vlw(
    ttf: Path, size: int, chars: str, variation: str | None
) -> tuple[bytes, dict]:
    font = ImageFont.truetype(str(ttf), size)

    if variation:
        try:
            font.set_variation_by_name(variation)
        except OSError as exc:
            names = [n.decode() for n in font.get_variation_names()]
            raise SystemExit(
                f"variation {variation!r} not available in {ttf.name}.\n"
                f"available: {', '.join(names)}\n  ({exc})"
            )

    ascent, descent = font.getmetrics()

    # Deduplicate and sort so TFT_eSPI's glyph lookup walks an ordered table.
    codepoints = sorted({ord(c) for c in chars})

    metrics = bytearray()
    bitmaps = bytearray()
    stats = {"glyphs": len(codepoints), "widest": 0, "tallest": 0}

    for cp in codepoints:
        ch = chr(cp)
        advance = round(font.getlength(ch))

        # getmask2 returns the antialiased coverage map plus its offset from
        # the pen position, which is exactly what the metrics table needs.
        mask, offset = font.getmask2(ch, mode="L")
        width, height = mask.size
        off_x, off_y = offset

        if width == 0 or height == 0:
            # Space and friends: no pixels, but the cursor still advances.
            width = height = off_x = off_y = 0
            pixels = b""
        else:
            pixels = bytes(mask)

        d_y = ascent - off_y  # baseline to top of the bitmap, positive up
        d_x = off_x

        metrics += struct.pack(">7i", cp, height, width, advance, d_y, d_x, 0)
        bitmaps += pixels

        stats["widest"] = max(stats["widest"], width)
        stats["tallest"] = max(stats["tallest"], height)

    header = struct.pack(">6i", len(codepoints), VLW_VERSION, size, 0, ascent, descent)
    blob = bytes(header + metrics + bitmaps)

    stats["ascent"] = ascent
    stats["descent"] = descent
    stats["bytes"] = len(blob)
    return blob, stats


def emit_header(name: str, blob: bytes, stats: dict, source: str) -> str:
    lines = [
        "// Generated by tools/mkvlw.py -- do not edit by hand.",
        f"// source: {source}",
        f"// glyphs: {stats['glyphs']}, ascent: {stats['ascent']}, "
        f"descent: {stats['descent']}, size: {stats['bytes']} bytes",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        f"const uint8_t {name}[] PROGMEM = {{",
    ]

    for offset in range(0, len(blob), 16):
        chunk = blob[offset : offset + 16]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))

    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ttf", type=Path)
    parser.add_argument("--size", type=int, required=True, help="pixel size")
    parser.add_argument("--name", required=True, help="C array name")
    parser.add_argument(
        "--chars",
        default="ascii",
        help="literal character set, or 'ascii' for all printable ASCII",
    )
    parser.add_argument("--variation", help="named instance of a variable font")
    parser.add_argument("--out", type=Path, required=True, help="output directory")
    parser.add_argument(
        "--list-variations", action="store_true", help="print named instances and exit"
    )
    args = parser.parse_args()

    if args.list_variations:
        font = ImageFont.truetype(str(args.ttf), args.size)
        for name in font.get_variation_names():
            print(name.decode())
        return 0

    chars = string.printable[:95] if args.chars == "ascii" else args.chars
    blob, stats = build_vlw(args.ttf, args.size, chars, args.variation)

    args.out.mkdir(parents=True, exist_ok=True)
    target = args.out / f"{args.name}.h"
    source = f"{args.ttf.name} @ {args.size}px" + (
        f" ({args.variation})" if args.variation else ""
    )
    target.write_text(emit_header(args.name, blob, stats, source), encoding="utf-8")

    print(
        f"{target.name}: {stats['glyphs']} glyphs, {stats['bytes']:,} bytes, "
        f"ascent {stats['ascent']}, tallest {stats['tallest']}px"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
